# Homework 1: Introduction to Machine Learning

## Question 1. Pandas version

What version of Pandas did you install?

In [35]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.1'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## Question 2. Records count

How many records are in the dataset?

In [5]:
df.info

<bound method DataFrame.info of       engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  

## Question 3. Fuel types

How many fuel types are presented in the dataset?

In [6]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

## Question 4. Missing values

How many columns in the dataset have missing values?

In [9]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

## Question 5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [11]:
df['origin'].unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [12]:
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

## Question 6. Median value of horsepower

 1. Find the median value of the horsepower column in the dataset.
 2. Next, calculate the most frequent value of the same horsepower column.
 3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
 4. Now, calculate the median value of horsepower once again.

In [13]:
df['horsepower'].median()

np.float64(149.0)

In [28]:
mode = df['horsepower'].mode()[0]
mode

np.float64(152.0)

In [29]:
df['horsepower'] = df['horsepower'].fillna(mode)

In [30]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [31]:
df['horsepower'].median()

np.float64(152.0)

## Question 7. Sum of weights

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

In [33]:
weights = df.loc[df['origin']=='Asia', ['vehicle_weight', 'model_year']].head(7)
weights

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [37]:
X = np.array(weights)
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [38]:
X_T = X.T

In [39]:
X_T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [40]:
XTX = np.matmul(X_T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [41]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [44]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [45]:
XTX_X = np.matmul(inv_XTX, X_T)
w = np.matmul(XTX_X, y)
w

array([0.01386421, 0.5049067 ])

In [46]:
w.sum()

np.float64(0.5187709081074016)