# Importing Numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

# Creating arrays

In [3]:
zeros_array = np.zeros(10)

In [4]:
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
ones_array = np.ones(10)

In [6]:
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
constant_array = np.full(10,3)

In [8]:
constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

# Converting Lists to Arrays

In [9]:
### let's say we have a list [1, 2, 3, 5, 7, 12]
### To make this an array:

array = np.array([1, 2, 3, 5, 7, 12])

In [10]:
array

array([ 1,  2,  3,  5,  7, 12])

In [11]:
### Another example:

list = [2, 3, 4]
array_from_list = np.array(list)

In [12]:
array_from_list

array([2, 3, 4])

In [13]:
### To access an element of an array, like object 4

array_from_list[1]

np.int64(3)

In [14]:
### To change the value of an object in an array:

array_from_list[1] = 10
array_from_list

array([ 2, 10,  4])

# Generating Ranges of Numbers|

In [15]:
### Creating a range with maximum of 10 no. of index

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

# Creating Arrays with Linear Spacing

In [17]:
### Create 11 numbers from 0 to 1

linespace_array = np.linspace(0, 1, 11) 
linespace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multidimensional Arrays

In [18]:
zeros_matrix = np.zeros((5, 2))
zeros_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
ones_matrix = np.ones((5, 2))
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
constant_matrix = np.full((5, 2), 3)
constant_matrix

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

# Indexing and Slicing Arrays

In [21]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
arr

array([[2, 3, 4],
       [4, 5, 6]])

Numpy array slicing

In [25]:
### Get the first row

arr[0]

array([2, 3, 4])

In [26]:
### Get the first column

arr[:,0]  ### Extracts all rows but only the first column

array([2, 4])

Numpy array indexing

In [27]:
### Access the first row, second column

arr[0, 1]

np.int64(3)

# Random Arrays