## Importing Numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

# Creating arrays

In [3]:
zeros_array = np.zeros(10)

In [4]:
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
ones_array = np.ones(10)

In [6]:
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
constant_array = np.full(10,3)

In [8]:
constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

# Converting Lists to Arrays

In [9]:
### let's say we have a list [1, 2, 3, 5, 7, 12]
### To make this an array:

array = np.array([1, 2, 3, 5, 7, 12])

In [10]:
array

array([ 1,  2,  3,  5,  7, 12])

In [11]:
### Another example:

list = [2, 3, 4]
array_from_list = np.array(list)

In [12]:
array_from_list

array([2, 3, 4])

In [13]:
### To access an element of an array, like object 4

array_from_list[1]

np.int64(3)

In [14]:
### To change the value of an object in an array:

array_from_list[1] = 10
array_from_list

array([ 2, 10,  4])

# Generating Ranges of Numbers|

In [15]:
### Creating a range with maximum of 10 no. of index

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

# Creating Arrays with Linear Spacing

In [19]:
### Create 11 numbers from 0 to 1

linespace_array = np.linspace(0, 1, 11) 
linespace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multidimensional Arrays

In [20]:
zeros_matrix = np.zeros((5, 2))
zeros_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
ones_matrix = np.ones((5, 2))
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
constant_matrix = np.full((5, 2), 3)
constant_matrix

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

# Indexing and Slicing Arrays

In [23]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
arr

array([[2, 3, 4],
       [4, 5, 6]])

Numpy array slicing

In [24]:
### Get the first row

arr[0]

array([2, 3, 4])

In [25]:
### Get the first column

arr[:,0]  ### Extracts all rows but only the first column

array([2, 4])

Numpy array indexing

In [26]:
### Access the first row, second column

arr[0, 1]

np.int64(3)

In [28]:
### Change the value of an object in an array

arr[1, 2] = 7

In [29]:
arr

array([[2, 3, 4],
       [4, 5, 7]])

In [31]:
### Change the value of a column

arr[:, 2] = [1, 2]

In [32]:
arr

array([[2, 3, 1],
       [4, 5, 2]])

# Generating Random Arrays

In [35]:
### Generating an array of random values with 5 rows and 2 columns
### Everytime we execute this, we get a different set of values

np.random.rand(5, 2)

array([[0.37087322, 0.50797583],
       [0.05031503, 0.46839112],
       [0.90203231, 0.89078558],
       [0.87461917, 0.18018274],
       [0.19721895, 0.02939331]])

In [38]:
np.random.seed(10)
random_array = np.random.rand(5, 2)
random_array

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [40]:
### To generate random integers
np.random.seed(10)
random_int = np.random.randint(low=0, high=100, size=(5, 2)) # where 0 is included and 100 is excluded so it generates numbers from 0 to 99
random_int

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

# Array Operations

## Element-wise operations

In [60]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [61]:
# Additon to each element
a + 1

array([1, 2, 3, 4, 5])

In [62]:
# Subtraction to each element
a - 0.01

array([-0.01,  0.99,  1.99,  2.99,  3.99])

In [63]:
# Multiplication to each element
a * 2

array([0, 2, 4, 6, 8])

In [64]:
# Division to each element
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [65]:
# Raising each element by a power
a ** 2

array([ 0,  1,  4,  9, 16])

In [66]:
# Combination of operations to each element
b = (10 + (a * 2))**2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

## Element-wise Operations with Two Arrays

In [67]:
a

array([0, 1, 2, 3, 4])

In [68]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [69]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [70]:
a >= b

array([False, False,  True,  True,  True])

In [71]:
### Which elements of a are greater than b

a[a>b]

array([2, 3, 4])

In [72]:
a == b

array([False, False, False, False, False])

## Summarizing operations

In [73]:
a 

array([0, 1, 2, 3, 4])

In [75]:
a.max()

np.int64(4)

In [76]:
a.min()

np.int64(0)

In [77]:
a.sum()

np.int64(10)

In [78]:
a.mean()

np.float64(2.0)

In [79]:
a.std()

np.float64(1.4142135623730951)