# Linear Algebra

In [1]:
import numpy as np

## Vector Operations

In [2]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [3]:
2 * u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

## Multiplication

### Vector-Vector Multiplication

In [6]:
u.shape

(4,)

In [7]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]  # to ensure that u and v have the same shape/size

    n = u.shape[0]  # n=4 since the shape of u is 4

    result = 0.0  # result will accumulate the sum
    
    for i in range(n):
        result = result + u[i] * v[i]  # multiply u and v and add them to the running total

    return result

In [8]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [9]:
# shortcut
u.dot(v)

np.int64(14)

### Matrix-Vector Multiplication

In [10]:
x = np.array([[2, 4, 5, 6], [1, 2, 1, 2], [3, 1, 2, 1]])
x

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [11]:
y = np.array([1, 0.5, 2, 1])
y

array([1. , 0.5, 2. , 1. ])

In [12]:
x.shape

(3, 4)

In [13]:
y.shape

(4,)

In [14]:
def matrix_vector_multiplication(x, y):
    assert x.shape[1] == v.shape[0] # the no. of columns in U must be equal to the number of elements in v

    num_rows = x.shape[0]  # U has 3 rows or 3x1

    result = np.zeros(num_rows) # make an empty array for result with 3 elements

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(x[i], y)  # for each element of array, perform v-v muyltiplication of each row of U with v

    return result

In [16]:
matrix_vector_multiplication(x, y)

array([20. ,  6. ,  8.5])

In [25]:
x.dot(y)

array([20. ,  6. ,  8.5])

### Matrix-Matrix Multiplication

In [17]:
a = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
a

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [18]:
b = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])
b

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [19]:
a.shape

(3, 4)

In [20]:
b.shape

(4, 3)

In [22]:
def matrix_matrix_multiplication(a, b):
    assert a.shape[1] == b.shape[0]  # must be equal to ensure that multiplication is possible

    # the size of result is 3x3
    num_rows = a.shape[0]
    num_cols = b.shape[1]
    
    result = np.zeros((num_rows, num_cols)) # prepare empty result matrix
    
    for i in range(num_cols):
        bi = b[:, i]  # take column i of b
        abi = matrix_vector_multiplication(a, bi) # multiply a with column i of b
        result[:, i] = abi  # put result in column i of result matrix
    
    return result

In [23]:
matrix_matrix_multiplication(a, b)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [26]:
a.dot(b)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [27]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
b

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [31]:
b.dot(I) # result must be equal to V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Inverse Matrix

In [35]:
Xs = x[:, [0, 1, 2]] # take the first 3 rows of the V matrix since Identity Matrix is a square matrix
Xs

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2]])

In [36]:
Xs_inv = np.linalg.inv(Xs)
Xs_inv

array([[-0.2       ,  0.2       ,  0.4       ],
       [-0.06666667,  0.73333333, -0.2       ],
       [ 0.33333333, -0.66666667, -0.        ]])

In [41]:
Xs_inv.dot(Xs).round(0) # result is an Identity matrix

array([[ 1., -0.,  0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])