# Linear Algebra

In [5]:
import numpy as np

## Vector Operations

In [6]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [7]:
2 * u

array([ 4,  8, 10, 12])

In [8]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [9]:
u + v

array([3, 4, 5, 8])

## Multiplication

### Vector-Vector Multiplication

In [10]:
u.shape

(4,)

In [11]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]  # to ensure that u and v have the same shape/size

    n = u.shape[0]  # n=4 since the shape of u is 4

    result = 0.0  # result will accumulate the sum
    
    for i in range(n):
        result = result + u[i] * v[i]  # multiply u and v and add them to the running total

    return result

In [12]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [13]:
# shortcut
u.dot(v)

np.int64(14)

### Matrix-Vector Multiplication

In [14]:
U = np.array([[2, 4, 5, 6], [1, 2, 1, 2], [3, 1, 2, 1]])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [16]:
v = np.array([1, 0.5, 2, 1])
v

array([1. , 0.5, 2. , 1. ])

In [17]:
U.shape

(3, 4)

In [18]:
v.shape

(4,)

In [30]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0] # the no. of columns in U must be equal to the number of elements in v

    num_rows = U.shape[0]  # U has 3 rows or 3x1

    result = np.zeros(num_rows) # make an empty array for result with 3 elements

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)  # for each element of array, perform v-v muyltiplication of each row of U with v

    return result

In [31]:
matrix_vector_multiplication(U, v)

array([20. ,  6. ,  8.5])

### Matrix-Matrix Multiplication

In [32]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [33]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [34]:
U.shape

(3, 4)

In [35]:
V.shape

(4, 3)

In [36]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]  # must be equal to ensure that multiplication is possible

    # the size of result is 3x3
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols)) # prepare empty result matrix
    
    for i in range(num_cols):
        vi = V[:, i]  # take column i of V
        Uvi = matrix_vector_multiplication(U, vi) # multiply U with column i of V
        result[:, i] = Uvi  # put result in column i of result matrix
    
    return result

In [37]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [38]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [45]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [48]:
V.dot(I) # result must be equal to V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Inverse Matrix

In [53]:
Vs = V[[0,1, 2]] # take the first 3 rows of the V matrix since Identity Matrix is a square matrix
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [54]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [56]:
Vs_inv.dot(Vs) # result is an Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])